% The function used to map input vectors into output vectors using a trained
%	network's weight metrices
%	x: The input
%	y: The output generated by the network
%	wi:	As of the wi in the return value of train function
%	wo:	As of the wo in the return value of train function
%	epsilon: as of epsilon in the argument of train function
%	c: as of c in the argument of train function
function y = neural_sim(x, wi, wo, epsilon, c)
	sz = size(x);
	% Generate argumented input
	X = [x, -1 * ones(sz(1), 1)];
	% calculate the values of the inputs into output layer
	h = 1 ./ pi .* epsilon ./ (X * wi' .^ 2 + epsilon ^ 2);
	% calculate the mapped value of x
	y = 1 ./ (1 + exp(-c .* (h * wo)));
end
